/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductImage } from './productImage';


export interface Product { 
    id?: number;
    name?: string;
    price?: number;
    images?: Array<ProductImage>;
}

