/**
 * My API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { Cart } from './cart';


export interface User { 
    id?: number;
    username?: string;
    password?: string;
    email?: string;
    roles?: Array<Role>;
    carts?: Array<Cart>;
    resetToken?: string;
}

